name: Accessibility Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  accessibility-lint:
    name: Accessibility Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with jsx-a11y plugin
        run: npm run lint:ci

  lighthouse-audit:
    name: Lighthouse Accessibility Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Serve and audit with Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          npm install -g serve

          # Start the server in the background
          serve -s dist -l 8080 &
          SERVER_PID=$!

          # Wait for server to be ready
          sleep 5

          # Run Lighthouse CI
          lhci autorun --config=lighthouserc.json || true

          # Kill the server
          kill $SERVER_PID

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

  accessibility-summary:
    name: Accessibility Summary
    runs-on: ubuntu-latest
    needs: [accessibility-lint, lighthouse-audit]
    if: always()
    steps:
      - name: Summary
        run: |
          echo "## Accessibility Testing Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ ESLint jsx-a11y checks completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Lighthouse accessibility audit completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📊 See job artifacts for detailed results" >> $GITHUB_STEP_SUMMARY
